---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: ic-claim-app

resources:
# wave 0
#infinispans.infinispan.org "infinispan" is forbidden: User "system:serviceaccount:my-app:argocd-argocd-application-controller" cannot patch resource "infinispans" in API group "infinispan.org" in the namespace "my-app"
#- infinispan-secret.yaml
# wave 1
#- infinispan-cluster.yaml
# wave 2
- deployment-app.yaml
- service-app.yaml
- route-app.yaml
