---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claimdb
  labels:
    app: claimdb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
