kind: Secret
apiVersion: v1
metadata:
  name: infinispan-generated-secret
data:
# credentials:
# - username: developer
#   password: VmpQuGPYG9AfyqKD
#   roles:
#   - admin
#   - controlRole
  identities.yaml: >-
    Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IGRldmVsb3BlcgogIHBhc3N3b3JkOiBWbXBRdUdQWUc5QWZ5cUtECiAgcm9sZXM6CiAgLSBhZG1pbgogIC0gY29udHJvbFJvbGUK
type: Opaque
