---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: ic-shared-infinispan

resources:
# wave 0
- namespace.yaml
- infinispan-secret.yaml
# wave 1
- infinispan-cluster.yaml
