---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: ic-shared-llm

resources:
# wave 0
- namespace.yaml
- fix-odf-config.yaml
- token.yaml
# wave 1
#- pvc.yaml
- pvc-ollama.yaml
#Removi pq n tem GPU para subir
#- deployment.yaml
#- service.yaml
- deployment-ollama.yaml
- service-ollama.yaml
- route-ollama.yaml
# wave 2
