---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-cache
  namespace: ic-shared-llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem