apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: claim-insurance-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  project: default
  source:
    path: gitops-app
    repoURL: https://github.com/viniciusfcf/ai-sandbox.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions: [CreateNamespace=false]
